# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(help_text='Titul del video.', max_length=100, unique=True)),
                ('tamany', models.IntegerField(help_text='Tamany del video.')),
                ('tipus', models.CharField(max_length=5)),
                ('data', models.DateField(auto_now_add=True, help_text='Data del video pujat.')),
                ('video', videos.models.ContentTypeRestrictedFileField(help_text='Video per pujar', upload_to='.')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
