# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(help_text='Video per pujar', upload_to='.'),
        ),
    ]
